// This file was auto-generated by ML.NET Model Builder. 

using System;
using System.Linq;
using JXB.BackendML.Model;
using Microsoft.ML;

namespace JXB.BackendML.ConsoleApp
{
    class Program
    {
        //Dataset to use for predictions 
        private const string DATA_FILEPATH = @"D:\Documents\MLTest\dataset.csv";

        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            ModelInput sampleData = CreateSingleDataSample(DATA_FILEPATH);

            // Make a single prediction on the sample data and print results
            ModelOutput predictionResult = ConsumeModel.Predict(sampleData);

            Console.WriteLine("Using model to make single prediction -- Comparing actual Col18 with predicted Col18 from sample data...\n\n");
            Console.WriteLine($"1: {sampleData.Col1}");
            Console.WriteLine($"2: {sampleData.Col2}");
            Console.WriteLine($"3: {sampleData.Col3}");
            Console.WriteLine($"4: {sampleData.Col4}");
            Console.WriteLine($"5: {sampleData.Col5}");
            Console.WriteLine($"6: {sampleData.Col6}");
            Console.WriteLine($"7: {sampleData.Col7}");
            Console.WriteLine($"8: {sampleData.Col8}");
            Console.WriteLine($"9: {sampleData.Col9}");
            Console.WriteLine($"10: {sampleData.Col10}");
            Console.WriteLine($"11: {sampleData.Col11}");
            Console.WriteLine($"12: {sampleData.Col12}");
            Console.WriteLine($"13: {sampleData.Col13}");
            Console.WriteLine($"14: {sampleData.Col14}");
            Console.WriteLine($"15: {sampleData.Col15}");
            Console.WriteLine($"16: {sampleData.Col16}");
            Console.WriteLine($"17: {sampleData.Col17}");
            Console.WriteLine($"\n\nActual Col18: {sampleData.Col18} \nPredicted Col18 value {predictionResult.Prediction} \nPredicted Col18 scores: [{String.Join(",", predictionResult.Score)}]\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }

        // Change this code to create your own sample data
        #region CreateSingleDataSample
        // Method to load single row of dataset to try a single prediction
        private static ModelInput CreateSingleDataSample(string dataFilePath)
        {
            // Create MLContext
            MLContext mlContext = new MLContext();

            // Load dataset
            IDataView dataView = mlContext.Data.LoadFromTextFile<ModelInput>(
                                            path: dataFilePath,
                                            hasHeader: true,
                                            separatorChar: ';',
                                            allowQuoting: true,
                                            allowSparse: false);

            // Use first line of dataset as model input
            // You can replace this with new test data (hardcoded or from end-user application)
            ModelInput sampleForPrediction = mlContext.Data.CreateEnumerable<ModelInput>(dataView, false)
                                                                        .First();
            return sampleForPrediction;
        }
        #endregion
    }
}
