// This file was auto-generated by ML.NET Model Builder. 

using System;
using Microsoft.ML;

namespace JXB.BackendML.Model
{
    public class ConsumeModel
    {
        // For more info on consuming ML.NET models, visit https://aka.ms/model-builder-consume
        // Method for consuming model in your app
        public  ModelOutput Predict(ModelInput input)
        {

            // Create new MLContext
            var mlContext = new MLContext();

            // Load model & create prediction engine
            var modelPath = AppDomain.CurrentDomain.BaseDirectory + "MLModel.zip";
            var mlModel = mlContext.Model.Load(modelPath, out var modelInputSchema);
            var predEngine = mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);

            // Use model to make prediction on input data
            var result = predEngine.Predict(input);
            return result;
        }
    }
}
