// This file was auto-generated by ML.NET Model Builder. 

using System;
using Microsoft.ML.Data;

namespace JXB.BackendML.Model
{
    public class ModelInput
    {
        [ColumnName("1"), LoadColumn(0),Label(Label = "1")]
        public float Col1 { get; set; }


        [ColumnName("2"), LoadColumn(1), Label(Label = "2")]
        public float Col2 { get; set; }


        [ColumnName("3"), LoadColumn(2), Label(Label = "3")]
        public float Col3 { get; set; }


        [ColumnName("4"), LoadColumn(3), Label(Label = "4")]
        public float Col4 { get; set; }


        [ColumnName("5"), LoadColumn(4), Label(Label = "5")]
        public float Col5 { get; set; }


        [ColumnName("6"), LoadColumn(5), Label(Label = "6")]
        public float Col6 { get; set; }


        [ColumnName("7"), LoadColumn(6), Label(Label = "7")]
        public float Col7 { get; set; }


        [ColumnName("8"), LoadColumn(7), Label(Label = "8")]
        public float Col8 { get; set; }


        [ColumnName("9"), LoadColumn(8), Label(Label = "9")]
        public float Col9 { get; set; }


        [ColumnName("10"), LoadColumn(9), Label(Label = "10")]
        public float Col10 { get; set; }


        [ColumnName("11"), LoadColumn(10), Label(Label = "11")]
        public float Col11 { get; set; }


        [ColumnName("12"), LoadColumn(11), Label(Label = "12")]
        public float Col12 { get; set; }


        [ColumnName("13"), LoadColumn(12), Label(Label = "13")]
        public float Col13 { get; set; }


        [ColumnName("14"), LoadColumn(13), Label(Label = "14")]
        public float Col14 { get; set; }


        [ColumnName("15"), LoadColumn(14), Label(Label = "15")]
        public float Col15 { get; set; }


        [ColumnName("16"), LoadColumn(15), Label(Label = "16")]
        public float Col16 { get; set; }


        [ColumnName("17"), LoadColumn(16), Label(Label = "17")]
        public float Col17 { get; set; }


        [ColumnName("18"), LoadColumn(17), Label(Label = "18")]
        public float Col18 { get; set; }


    }

    public class LabelAttribute : Attribute
    {
        public string Label { get; set; }
    }
}
